// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBah5uGBygZInJcVY6Yx6D_a_DIayiydmY',
    appId: '1:527582152780:web:47fc3238d3ac60c3fa0ce9',
    messagingSenderId: '527582152780',
    projectId: 'chattappv1',
    authDomain: 'chattappv1.firebaseapp.com',
    storageBucket: 'chattappv1.appspot.com',
    measurementId: 'G-EQPEY2XF6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAzH8zGmz2e7NfWYg9rGPqRP13_MumW-A',
    appId: '1:527582152780:android:549a99d54d83a26cfa0ce9',
    messagingSenderId: '527582152780',
    projectId: 'chattappv1',
    storageBucket: 'chattappv1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQuTOZv89goquSqScfL5mIrfKqTheHdgQ',
    appId: '1:527582152780:ios:817e74cb3a66f2cffa0ce9',
    messagingSenderId: '527582152780',
    projectId: 'chattappv1',
    storageBucket: 'chattappv1.appspot.com',
    iosBundleId: 'com.example.chattappv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQuTOZv89goquSqScfL5mIrfKqTheHdgQ',
    appId: '1:527582152780:ios:817e74cb3a66f2cffa0ce9',
    messagingSenderId: '527582152780',
    projectId: 'chattappv1',
    storageBucket: 'chattappv1.appspot.com',
    iosBundleId: 'com.example.chattappv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBah5uGBygZInJcVY6Yx6D_a_DIayiydmY',
    appId: '1:527582152780:web:2f5ed90ee6cba924fa0ce9',
    messagingSenderId: '527582152780',
    projectId: 'chattappv1',
    authDomain: 'chattappv1.firebaseapp.com',
    storageBucket: 'chattappv1.appspot.com',
    measurementId: 'G-H236JJDDTG',
  );
}
